import type { FormDefinition } from "@/lib/form-definition";

const escape = (value: unknown) => String(value ?? "").replace(/[&<>"']/gu, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!);

function selectedValues(value: unknown) {
  return new Set(Array.isArray(value) ? value.map(String) : value === undefined || value === null ? [] : [String(value)]);
}

function control(field: FormDefinition["fields"][number], value?: unknown) {
  const attrs = `id="${escape(field.key)}" name="${escape(field.key)}"${field.required ? " required" : ""}${field.placeholder ? ` placeholder="${escape(field.placeholder)}"` : ""}`;
  const selected = selectedValues(value);
  if (field.type === "textarea") return `<textarea ${attrs} rows="5">${escape(value)}</textarea>`;
  if (field.type === "select") return `<select ${attrs}><option value="">Choose one</option>${field.options!.map((o) => `<option value="${escape(o.value)}"${selected.has(o.value) ? " selected" : ""}>${escape(o.label)}</option>`).join("")}</select>`;
  if (field.type === "radio" || field.type === "checkbox") return `<div class="choices">${field.options!.map((o) => `<label class="choice"><input type="${field.type}" name="${escape(field.key)}" value="${escape(o.value)}"${field.required ? " required" : ""}${selected.has(o.value) ? " checked" : ""}> <span>${escape(o.label)}</span></label>`).join("")}</div>`;
  if (field.type === "consent") return `<label class="choice"><input type="checkbox" ${attrs} value="yes"${selected.has("yes") ? " checked" : ""}> <span>${escape(field.label)}</span></label>`;
  if (field.type === "file") return `<input type="file" ${attrs}${field.validation?.acceptedFileTypes?.length ? ` accept="${escape(field.validation.acceptedFileTypes.join(","))}"` : ""}><p class="file-hint">Private upload, up to ${field.validation?.maxFileSizeMb ?? 2} MB.</p>`;
  const type = ["email", "number", "tel", "url", "date"].includes(field.type) ? field.type : "text";
  return `<input type="${type}" ${attrs} value="${escape(value)}"${field.validation?.minLength !== undefined ? ` minlength="${field.validation.minLength}"` : ""}${field.validation?.maxLength !== undefined ? ` maxlength="${field.validation.maxLength}"` : ""}${field.validation?.min !== undefined ? ` min="${field.validation.min}"` : ""}${field.validation?.max !== undefined ? ` max="${field.validation.max}"` : ""}>`;
}

export function renderPublicForm(input: { definition: FormDefinition; endpointId: string; action: string; siteKey: string; submissionId: string; message?: string; formError?: string; errors?: Record<string,string>; values?: Record<string,unknown> }) {
  const { definition } = input;
  const visibleFields = definition.fields.filter((field) => !field.hidden);
  const fields = visibleFields.map((field, index) => `<div class="field"><div class="field-number">${String(index + 1).padStart(2, "0")}</div><div><label for="${escape(field.key)}">${escape(field.label)}${field.required ? " <span aria-hidden=\"true\">*</span>" : ""}</label>${field.description ? `<p>${escape(field.description)}</p>` : ""}${control(field,input.values?.[field.key])}${input.errors?.[field.key] ? `<p class="error" role="alert">${escape(input.errors[field.key])}</p>` : ""}</div></div>`).join("");
  const theme = definition.presentation;
  const themeStyle = `--canvas:${theme.backgroundColor};--text:${theme.textColor};--lime:${theme.accentColor}`;
  return `<!doctype html><html lang="en" data-font="${escape(theme.fontFamily)}" data-spacing="${escape(theme.spacing)}" data-button="${escape(theme.buttonStyle)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(definition.title)} · Jobing Forms</title><link rel="stylesheet" href="/forms/public-form.css"><script src="/forms/public-form.js"></script><script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer></script></head><body style="${themeStyle}"><main><header><a href="https://jobing.site/forms" class="brand">Jobing <span>Forms</span></a><p class="eyebrow">Secure response</p><h1>${escape(definition.title)}</h1>${definition.description ? `<p class="lede">${escape(definition.description)}</p>` : ""}</header>${input.message ? `<section class="success" role="status"><strong>${escape(definition.confirmation.title)}</strong><p>${escape(input.message)}</p></section>` : `<form method="post" enctype="multipart/form-data" action="${escape(input.action)}" data-public-form>${input.formError ? `<section class="form-error" role="alert"><strong>We could not send your response.</strong><p>${escape(input.formError)}</p></section>` : ""}<input type="hidden" name="_submission_id" value="${escape(input.submissionId)}"><input type="hidden" name="_jobing_form_context" value="hosted">${fields}<section class="security-check" aria-labelledby="security-check-title"><strong id="security-check-title">Protected automatically</strong><p data-turnstile-status aria-live="polite">Finishing a quick security check…</p><div class="cf-turnstile" data-sitekey="${escape(input.siteKey)}" data-action="turnstile-spin-v1" data-appearance="interaction-only" data-size="flexible" data-retry="auto" data-refresh-expired="auto" data-refresh-timeout="auto" data-callback="jobingTurnstileReady" data-error-callback="jobingTurnstileError" data-expired-callback="jobingTurnstileExpired" data-timeout-callback="jobingTurnstileExpired"></div><noscript>JavaScript is required to complete the security check.</noscript></section><button type="submit" disabled data-submit-button>Send response</button><p class="privacy">Protected by Cloudflare Turnstile. Your response is sent securely to the form owner.</p></form>`}</main></body></html>`;
}
