import React from "react";
import { DashboardLayout } from "@/components/DashboardLayout";
import { LegalContent, LegalSection } from "@/components/LegalContent";

export const metadata = {
  title: "Terms & Conditions | Jobing AI",
};

export default function TermsPage() {
  return (
    <DashboardLayout>
      <LegalContent title="Terms & Conditions" lastUpdated="March 27, 2026">
        <LegalSection title="1. Acceptance of Terms">
          <p>
            By accessing or using Jobing AI (&quot;the Service&quot;), you agree to be bound by these Terms and Conditions. If you do not agree to all of these terms, do not use the service.
          </p>
        </LegalSection>

        <LegalSection title="2. Description of Service">
          <p>
            Jobing AI provides an AI-powered platform for building and tailoring professional resumes. The Service uses advanced large language models to analyze user data and generate professional content based on provided job descriptions.
          </p>
        </LegalSection>

        <LegalSection title="3. AI Disclaimer & Accuracy">
          <p>
            <strong>Content Generation:</strong> You acknowledge that the content generated by Jobing AI is produced by artificial intelligence. While we strive for high accuracy, AI can occasionally produce incorrect, biased, or incomplete information.
          </p>
          <p>
            <strong>User Responsibility:</strong> It is your sole responsibility to review, verify, and edit any content generated by the Service before using it for job applications. Jobing AI is not responsible for any outcomes resulting from the use of generated content.
          </p>
        </LegalSection>

        <LegalSection title="4. User Obligations">
          <ul className="list-disc pl-5 space-y-2">
            <li>You must provide accurate and truthful information about your professional background.</li>
            <li>You may not use the Service for any illegal or unauthorized purpose.</li>
            <li>You are responsible for maintaining the security of your account and credentials.</li>
            <li>You agree not to attempt to reverse engineer or bypass any safety filters of the AI models.</li>
          </ul>
        </LegalSection>

        <LegalSection title="5. Intellectual Property">
          <p>
            The underlying technology, design, and original content of Jobing AI are the exclusive property of Jobing AI. However, you retain ownership of the personal data you provide and the final resumes you generate using the Service.
          </p>
        </LegalSection>

        <LegalSection title="6. Limitation of Liability">
          <p>
            In no event shall Jobing AI, its directors, employees, or partners be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, or other intangible losses.
          </p>
        </LegalSection>

        <LegalSection title="7. Modifications to Service">
          <p>
            We reserve the right to modify or discontinue, temporarily or permanently, the Service with or without notice. We may also update these Terms from time to time. Your continued use of the Service constitutes acceptance of the new Terms.
          </p>
        </LegalSection>
      </LegalContent>
    </DashboardLayout>
  );
}
